const $=id=>document.getElementById(id);const canvas=$('game'),ctx=canvas.getContext('2d');
const DEFAULT={version:3,best:0,totalPops:0,coins:0,xp:0,level:1,campaign:1,settings:{sound:true,haptics:true,reduced:false}};
const Store=(()=>{let data=structuredClone(DEFAULT),timer=0;const normalize=x=>{const n=structuredClone(DEFAULT);if(!x||typeof x!=='object')return n;for(const k of ['best','totalPops','coins','xp','level','campaign'])n[k]=Math.max(k==='level'||k==='campaign'?1:0,Number(x[k])||n[k]);n.settings={...n.settings,...(x.settings||{})};return n};function load(){try{data=normalize(JSON.parse(localStorage.getItem('balloon_blitz_v3')||'null'))}catch(e){console.error('Save recovery',e);data=structuredClone(DEFAULT)}return data}function flush(){clearTimeout(timer);try{localStorage.setItem('balloon_blitz_v3',JSON.stringify(data));return true}catch(e){toast('Progress could not be saved');console.error(e);return false}}function save(){clearTimeout(timer);timer=setTimeout(flush,300)}function reset(){data=structuredClone(DEFAULT);flush()}addEventListener('pagehide',flush);document.addEventListener('visibilitychange',()=>document.hidden&&flush());return{load,save,flush,reset,get data(){return data}}})();
const Audio=(()=>{let ac;function init(){if(!Store.data.settings.sound)return null;ac??=new(window.AudioContext||window.webkitAudioContext)();if(ac.state==='suspended')ac.resume();return ac}function tone(freq=500,d=.08,type='sine',gain=.14){const a=init();if(!a)return;const o=a.createOscillator(),g=a.createGain(),t=a.currentTime;o.type=type;o.frequency.setValueAtTime(freq,t);o.frequency.exponentialRampToValueAtTime(Math.max(70,freq*.55),t+d);g.gain.setValueAtTime(gain,t);g.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(g);g.connect(a.destination);o.start(t);o.stop(t+d+.01)}function pop(combo){tone(360+Math.min(combo,12)*35,.08,'sine')}function bad(){tone(150,.18,'sawtooth',.18)}function win(){[440,554,659,880].forEach((f,i)=>setTimeout(()=>tone(f,.2,'triangle'),i*70))}return{init,pop,bad,win}})();
let dpr=1,w=0,h=0,state='home',mode='blitz',selected='blitz',score=0,combo=1,bestCombo=1,time=60,lives=3,popped=0,level=1,balls=[],particles=[],raf=0,last=0,hudSecond=-1,runId=0;
const MODES={blitz:{label:'BLITZ',target:'TIME'},survival:{label:'SURVIVAL',target:'LIVES'},campaign:{label:'CAMPAIGN',target:'TIME'}};
function resize(){w=innerWidth;h=innerHeight;dpr=Math.min(devicePixelRatio||1,2);canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize,{passive:true});resize();
class Balloon{constructor(){this.reset(true)}reset(initial=false){this.r=24+Math.random()*13;this.x=this.r+Math.random()*(w-this.r*2);this.y=initial?Math.random()*h:h+this.r+Math.random()*80;this.speed=75+Math.random()*85+(mode==='survival'?popped*.12:0)+(mode==='campaign'?level*2:0);this.color=['#f05b54','#368bd6','#49a95b','#f1b42f','#9b70bd'][Math.floor(Math.random()*5)];this.gold=Math.random()<.08;this.dead=false;this.phase=Math.random()*6}update(dt){this.y-=this.speed*dt;this.phase+=dt*2;if(this.y<-this.r){if(mode==='survival'){lives--;Audio.bad();if(lives<=0){finish(false);return}}this.reset()}}draw(){const x=this.x+Math.sin(this.phase)*8,y=this.y,r=this.r;ctx.save();ctx.fillStyle=this.gold?'#ffd12f':this.color;ctx.strokeStyle='#342a27aa';ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(x,y,r*.86,r,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#fff9';ctx.beginPath();ctx.ellipse(x-r*.28,y-r*.35,r*.15,r*.25,-.5,0,Math.PI*2);ctx.fill();ctx.fillStyle='#342a27';ctx.beginPath();ctx.moveTo(x-5,y+r);ctx.lineTo(x+5,y+r);ctx.lineTo(x,y+r+9);ctx.fill();ctx.restore()}hit(x,y){const dx=x-(this.x+Math.sin(this.phase)*8),dy=y-this.y;return dx*dx+dy*dy<(this.r+10)**2}}
class Particle{constructor(x,y,c){this.x=x;this.y=y;this.c=c;const a=Math.random()*Math.PI*2,s=80+Math.random()*140;this.vx=Math.cos(a)*s;this.vy=Math.sin(a)*s;this.life=1}update(dt){this.x+=this.vx*dt;this.y+=this.vy*dt;this.vy+=200*dt;this.life-=dt*2.4}draw(){ctx.globalAlpha=Math.max(0,this.life);ctx.fillStyle=this.c;ctx.fillRect(this.x,this.y,4,4);ctx.globalAlpha=1}}
function setScreen(id){['home','pause','result','settings'].forEach(x=>$(x).classList.toggle('hidden',x!==id));$('hud').classList.toggle('hidden',state!=='playing'&&state!=='paused');canvas.style.display=state==='playing'||state==='paused'?'block':'none';document.body.classList.toggle('playing',state==='playing')}
function updateHome(){const s=Store.data;$('best').textContent=s.best.toLocaleString();$('pops').textContent=s.totalPops.toLocaleString();$('coins').textContent=s.coins.toLocaleString();$('rank').textContent=`${s.level<4?'ROOKIE':s.level<8?'SKILLED':'MASTER'} · LV ${s.level}`;$('campaignMeta').textContent=`Stage ${s.campaign} of 30`}
function updateHud(force=false){$('score').textContent=score.toLocaleString();$('combo').textContent=`×${combo}`;$('modeLabel').textContent=mode==='campaign'?`STAGE ${level}`:MODES[mode].label;$('targetLabel').textContent=MODES[mode].target;$('target').textContent=mode==='survival'?'❤️'.repeat(Math.max(0,lives))||'💀':Math.max(0,Math.ceil(time));if(force)hudSecond=Math.ceil(time)}
function start(next=selected){cancelAnimationFrame(raf);runId++;mode=next;state='playing';score=0;combo=1;bestCombo=1;popped=0;lives=3;level=Store.data.campaign;time=mode==='blitz'?60:mode==='campaign'?Math.max(32,46-level*.35):0;balls=Array.from({length:Math.min(18,10+Math.floor(w/90))},()=>new Balloon);particles=[];last=performance.now();hudSecond=-1;Audio.init();updateHud(true);setScreen(null);raf=requestAnimationFrame(loop)}
function finish(cleared=true){if(state!=='playing')return;state='result';cancelAnimationFrame(raf);const s=Store.data;s.totalPops+=popped;s.best=Math.max(s.best,score);const earned=Math.floor(score/120)+popped;s.coins+=earned;s.xp+=Math.floor(score/25)+popped*2;s.level=1+Math.floor(Math.sqrt(s.xp/150));if(mode==='campaign'&&cleared&&level===s.campaign&&s.campaign<30)s.campaign++;Store.flush();$('resultKicker').textContent=mode==='campaign'?(cleared?'STAGE CLEARED':'TIME UP'):'RUN COMPLETE';$('resultTitle').textContent=score>s.best?'New best!':'Great run!';$('finalScore').textContent=score.toLocaleString();$('resultText').textContent=`${popped} pops · ×${bestCombo} combo · +${earned} coins`;Audio.win();setScreen('result')}
function loop(now){if(state!=='playing')return;const dt=Math.min((now-last)/1000,.05);last=now;if(mode!=='survival'){time-=dt;if(time<=0){finish(mode!=='campaign');return}}ctx.clearRect(0,0,w,h);for(const b of balls){b.update(dt);if(state!=='playing')return;b.draw()}for(let i=particles.length-1;i>=0;i--){particles[i].update(dt);particles[i].draw();if(particles[i].life<=0)particles.splice(i,1)}if(mode==='campaign'&&popped>=12+level*2){finish(true);return}const sec=Math.ceil(time);if(sec!==hudSecond||mode==='survival'){hudSecond=sec;updateHud()}raf=requestAnimationFrame(loop)}
function tap(x,y){if(state!=='playing')return;for(let i=balls.length-1;i>=0;i--){const b=balls[i];if(b.hit(x,y)){const pts=(b.gold?100:20)*combo;score+=pts;popped++;combo++;bestCombo=Math.max(bestCombo,combo);Audio.pop(combo);if(Store.data.settings.haptics&&navigator.vibrate)navigator.vibrate(10);if(!Store.data.settings.reduced)for(let n=0;n<10;n++)particles.push(new Particle(x,y,b.gold?'#ffd12f':b.color));b.reset();updateHud();return}}combo=1;updateHud()}
canvas.addEventListener('pointerdown',e=>{e.preventDefault();tap(e.clientX,e.clientY)});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='playing')pause()});
function pause(){if(state!=='playing')return;state='paused';cancelAnimationFrame(raf);setScreen('pause')}function resume(){if(state!=='paused')return;state='playing';last=performance.now();setScreen(null);raf=requestAnimationFrame(loop)}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),1800)}
document.querySelectorAll('[data-mode]').forEach(btn=>btn.addEventListener('click',()=>{selected=btn.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('selected',x===btn));$('playBtn').textContent=`PLAY ${selected.toUpperCase()}`}));document.querySelector('[data-mode="blitz"]').classList.add('selected');
$('playBtn').onclick=()=>start();$('pauseBtn').onclick=pause;$('resumeBtn').onclick=resume;$('restartBtn').onclick=()=>start(mode);$('quitBtn').onclick=()=>{state='home';cancelAnimationFrame(raf);updateHome();setScreen('home')};$('againBtn').onclick=()=>start(mode);$('homeBtn').onclick=()=>{state='home';updateHome();setScreen('home')};$('settingsBtn').onclick=()=>{const s=Store.data.settings;$('soundToggle').checked=s.sound;$('hapticToggle').checked=s.haptics;$('effectsToggle').checked=s.reduced;setScreen('settings')};$('closeSettingsBtn').onclick=()=>{const s=Store.data.settings;s.sound=$('soundToggle').checked;s.haptics=$('hapticToggle').checked;s.reduced=$('effectsToggle').checked;Store.flush();setScreen('home')};$('resetBtn').onclick=()=>{if(confirm('Reset all Balloon Blitz progress?')){Store.reset();updateHome();toast('Progress reset');setScreen('home')}};
window.addEventListener('error',e=>{console.error('Balloon Blitz error',e.error||e.message);toast('Something went wrong — your progress is safe')});Store.load();updateHome();setScreen('home');if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.error));
